(cl:defpackage armadillo2_msgs-srv
  (:use )
  (:export
   "PANTILT"
   "<PANTILT-REQUEST>"
   "PANTILT-REQUEST"
   "<PANTILT-RESPONSE>"
   "PANTILT-RESPONSE"
   "QUERYTRAJECTORYSTATE"
   "<QUERYTRAJECTORYSTATE-REQUEST>"
   "QUERYTRAJECTORYSTATE-REQUEST"
   "<QUERYTRAJECTORYSTATE-RESPONSE>"
   "QUERYTRAJECTORYSTATE-RESPONSE"
   "SWITCHCAMTOPIC"
   "<SWITCHCAMTOPIC-REQUEST>"
   "SWITCHCAMTOPIC-REQUEST"
   "<SWITCHCAMTOPIC-RESPONSE>"
   "SWITCHCAMTOPIC-RESPONSE"
  ))

