(cl:defpackage armadillo2_msgs-msg
  (:use )
  (:export
   "<JOINTTRAJECTORYCONTROLLERSTATE>"
   "JOINTTRAJECTORYCONTROLLERSTATE"
   "<POINTHEADACTION>"
   "POINTHEADACTION"
   "<POINTHEADACTIONFEEDBACK>"
   "POINTHEADACTIONFEEDBACK"
   "<POINTHEADACTIONGOAL>"
   "POINTHEADACTIONGOAL"
   "<POINTHEADACTIONRESULT>"
   "POINTHEADACTIONRESULT"
   "<POINTHEADFEEDBACK>"
   "POINTHEADFEEDBACK"
   "<POINTHEADGOAL>"
   "POINTHEADGOAL"
   "<POINTHEADRESULT>"
   "POINTHEADRESULT"
  ))

