// Generated by gencpp from file armadillo2_msgs/PanTiltRequest.msg
// DO NOT EDIT!


#ifndef ARMADILLO2_MSGS_MESSAGE_PANTILTREQUEST_H
#define ARMADILLO2_MSGS_MESSAGE_PANTILTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armadillo2_msgs
{
template <class ContainerAllocator>
struct PanTiltRequest_
{
  typedef PanTiltRequest_<ContainerAllocator> Type;

  PanTiltRequest_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  PanTiltRequest_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;





  typedef boost::shared_ptr< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PanTiltRequest_

typedef ::armadillo2_msgs::PanTiltRequest_<std::allocator<void> > PanTiltRequest;

typedef boost::shared_ptr< ::armadillo2_msgs::PanTiltRequest > PanTiltRequestPtr;
typedef boost::shared_ptr< ::armadillo2_msgs::PanTiltRequest const> PanTiltRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace armadillo2_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'armadillo2_msgs': ['/home/zeged/catkin_ws/src/armadillo2/armadillo2_msgs/msgs', '/home/zeged/catkin_ws/devel/share/armadillo2_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938e11f380abc0513a5b7367d0f157bf";
  }

  static const char* value(const ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938e11f380abc051ULL;
  static const uint64_t static_value2 = 0x3a5b7367d0f157bfULL;
};

template<class ContainerAllocator>
struct DataType< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armadillo2_msgs/PanTiltRequest";
  }

  static const char* value(const ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 pan\n\
float32 tilt\n\
";
  }

  static const char* value(const ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanTiltRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armadillo2_msgs::PanTiltRequest_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMADILLO2_MSGS_MESSAGE_PANTILTREQUEST_H
