// Generated by gencpp from file armadillo2_msgs/PanTilt.msg
// DO NOT EDIT!


#ifndef ARMADILLO2_MSGS_MESSAGE_PANTILT_H
#define ARMADILLO2_MSGS_MESSAGE_PANTILT_H

#include <ros/service_traits.h>


#include <armadillo2_msgs/PanTiltRequest.h>
#include <armadillo2_msgs/PanTiltResponse.h>


namespace armadillo2_msgs
{

struct PanTilt
{

typedef PanTiltRequest Request;
typedef PanTiltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PanTilt
} // namespace armadillo2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armadillo2_msgs::PanTilt > {
  static const char* value()
  {
    return "938e11f380abc0513a5b7367d0f157bf";
  }

  static const char* value(const ::armadillo2_msgs::PanTilt&) { return value(); }
};

template<>
struct DataType< ::armadillo2_msgs::PanTilt > {
  static const char* value()
  {
    return "armadillo2_msgs/PanTilt";
  }

  static const char* value(const ::armadillo2_msgs::PanTilt&) { return value(); }
};


// service_traits::MD5Sum< ::armadillo2_msgs::PanTiltRequest> should match 
// service_traits::MD5Sum< ::armadillo2_msgs::PanTilt > 
template<>
struct MD5Sum< ::armadillo2_msgs::PanTiltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armadillo2_msgs::PanTilt >::value();
  }
  static const char* value(const ::armadillo2_msgs::PanTiltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armadillo2_msgs::PanTiltRequest> should match 
// service_traits::DataType< ::armadillo2_msgs::PanTilt > 
template<>
struct DataType< ::armadillo2_msgs::PanTiltRequest>
{
  static const char* value()
  {
    return DataType< ::armadillo2_msgs::PanTilt >::value();
  }
  static const char* value(const ::armadillo2_msgs::PanTiltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armadillo2_msgs::PanTiltResponse> should match 
// service_traits::MD5Sum< ::armadillo2_msgs::PanTilt > 
template<>
struct MD5Sum< ::armadillo2_msgs::PanTiltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armadillo2_msgs::PanTilt >::value();
  }
  static const char* value(const ::armadillo2_msgs::PanTiltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armadillo2_msgs::PanTiltResponse> should match 
// service_traits::DataType< ::armadillo2_msgs::PanTilt > 
template<>
struct DataType< ::armadillo2_msgs::PanTiltResponse>
{
  static const char* value()
  {
    return DataType< ::armadillo2_msgs::PanTilt >::value();
  }
  static const char* value(const ::armadillo2_msgs::PanTiltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMADILLO2_MSGS_MESSAGE_PANTILT_H
