// Generated by gencpp from file armadillo2_msgs/QueryTrajectoryState.msg
// DO NOT EDIT!


#ifndef ARMADILLO2_MSGS_MESSAGE_QUERYTRAJECTORYSTATE_H
#define ARMADILLO2_MSGS_MESSAGE_QUERYTRAJECTORYSTATE_H

#include <ros/service_traits.h>


#include <armadillo2_msgs/QueryTrajectoryStateRequest.h>
#include <armadillo2_msgs/QueryTrajectoryStateResponse.h>


namespace armadillo2_msgs
{

struct QueryTrajectoryState
{

typedef QueryTrajectoryStateRequest Request;
typedef QueryTrajectoryStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryTrajectoryState
} // namespace armadillo2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armadillo2_msgs::QueryTrajectoryState > {
  static const char* value()
  {
    return "ec93cdecbd8062d761aa52b7c90cd44b";
  }

  static const char* value(const ::armadillo2_msgs::QueryTrajectoryState&) { return value(); }
};

template<>
struct DataType< ::armadillo2_msgs::QueryTrajectoryState > {
  static const char* value()
  {
    return "armadillo2_msgs/QueryTrajectoryState";
  }

  static const char* value(const ::armadillo2_msgs::QueryTrajectoryState&) { return value(); }
};


// service_traits::MD5Sum< ::armadillo2_msgs::QueryTrajectoryStateRequest> should match 
// service_traits::MD5Sum< ::armadillo2_msgs::QueryTrajectoryState > 
template<>
struct MD5Sum< ::armadillo2_msgs::QueryTrajectoryStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armadillo2_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::armadillo2_msgs::QueryTrajectoryStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armadillo2_msgs::QueryTrajectoryStateRequest> should match 
// service_traits::DataType< ::armadillo2_msgs::QueryTrajectoryState > 
template<>
struct DataType< ::armadillo2_msgs::QueryTrajectoryStateRequest>
{
  static const char* value()
  {
    return DataType< ::armadillo2_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::armadillo2_msgs::QueryTrajectoryStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armadillo2_msgs::QueryTrajectoryStateResponse> should match 
// service_traits::MD5Sum< ::armadillo2_msgs::QueryTrajectoryState > 
template<>
struct MD5Sum< ::armadillo2_msgs::QueryTrajectoryStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armadillo2_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::armadillo2_msgs::QueryTrajectoryStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armadillo2_msgs::QueryTrajectoryStateResponse> should match 
// service_traits::DataType< ::armadillo2_msgs::QueryTrajectoryState > 
template<>
struct DataType< ::armadillo2_msgs::QueryTrajectoryStateResponse>
{
  static const char* value()
  {
    return DataType< ::armadillo2_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::armadillo2_msgs::QueryTrajectoryStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMADILLO2_MSGS_MESSAGE_QUERYTRAJECTORYSTATE_H
