// Generated by gencpp from file armadillo2_msgs/SwitchCamTopic.msg
// DO NOT EDIT!


#ifndef ARMADILLO2_MSGS_MESSAGE_SWITCHCAMTOPIC_H
#define ARMADILLO2_MSGS_MESSAGE_SWITCHCAMTOPIC_H

#include <ros/service_traits.h>


#include <armadillo2_msgs/SwitchCamTopicRequest.h>
#include <armadillo2_msgs/SwitchCamTopicResponse.h>


namespace armadillo2_msgs
{

struct SwitchCamTopic
{

typedef SwitchCamTopicRequest Request;
typedef SwitchCamTopicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchCamTopic
} // namespace armadillo2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armadillo2_msgs::SwitchCamTopic > {
  static const char* value()
  {
    return "b6b3b805312bdb3b12a4c8cc137ba6be";
  }

  static const char* value(const ::armadillo2_msgs::SwitchCamTopic&) { return value(); }
};

template<>
struct DataType< ::armadillo2_msgs::SwitchCamTopic > {
  static const char* value()
  {
    return "armadillo2_msgs/SwitchCamTopic";
  }

  static const char* value(const ::armadillo2_msgs::SwitchCamTopic&) { return value(); }
};


// service_traits::MD5Sum< ::armadillo2_msgs::SwitchCamTopicRequest> should match 
// service_traits::MD5Sum< ::armadillo2_msgs::SwitchCamTopic > 
template<>
struct MD5Sum< ::armadillo2_msgs::SwitchCamTopicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armadillo2_msgs::SwitchCamTopic >::value();
  }
  static const char* value(const ::armadillo2_msgs::SwitchCamTopicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armadillo2_msgs::SwitchCamTopicRequest> should match 
// service_traits::DataType< ::armadillo2_msgs::SwitchCamTopic > 
template<>
struct DataType< ::armadillo2_msgs::SwitchCamTopicRequest>
{
  static const char* value()
  {
    return DataType< ::armadillo2_msgs::SwitchCamTopic >::value();
  }
  static const char* value(const ::armadillo2_msgs::SwitchCamTopicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armadillo2_msgs::SwitchCamTopicResponse> should match 
// service_traits::MD5Sum< ::armadillo2_msgs::SwitchCamTopic > 
template<>
struct MD5Sum< ::armadillo2_msgs::SwitchCamTopicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armadillo2_msgs::SwitchCamTopic >::value();
  }
  static const char* value(const ::armadillo2_msgs::SwitchCamTopicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armadillo2_msgs::SwitchCamTopicResponse> should match 
// service_traits::DataType< ::armadillo2_msgs::SwitchCamTopic > 
template<>
struct DataType< ::armadillo2_msgs::SwitchCamTopicResponse>
{
  static const char* value()
  {
    return DataType< ::armadillo2_msgs::SwitchCamTopic >::value();
  }
  static const char* value(const ::armadillo2_msgs::SwitchCamTopicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMADILLO2_MSGS_MESSAGE_SWITCHCAMTOPIC_H
